### ISSUE TITLE
Accept const bool member functions as guards

### ISSUE THREAD

**Issue by pmf** [tinverse/tsm#11]
It would be good if the `add()` method (for defining transition tables) would accept const bool member functions (currently only accepts non-const).

Might prepare a PR for this if I get to it.

(Off topic: I like this project a lot so far; very intuitive interface!)

**Comment by dibsonmuad** [comment]
Thanks! I was on vacation (and sick afterward)! Can you look at this and comment? https://github.com/tinverse/tsm/pull/12

**Comment by dibsonmuad** [comment]
Merged above PR. Closing issue.
