### ISSUE TITLE
Replace GTest with Catch2 unit testing framework

### ISSUE THREAD

**Issue by dibsonmuad** [tinverse/tsm#6]
After researching ways of reducing dependencies on 3rd party libraries, I decided to replace gtest with catch2, which is a header only c++ library. This makes integration easier and hopefully with make tsm more accessible on windows platform as well. The user will not have to deal with gtest shared/static library issues.

**Comment by dibsonmuad** [comment]
GTest has been replaced with Catch2. CMake is no longer needed to use tsm.

**Comment by DJuego** [comment]
Thank you very much for your work!! 

DJuego
